### PR TITLE
made POSIX-compliant (solving './check: function: not found')

### PR DESCRIPTION
**Pull request by sirfoga**

### CODE REVIEW

**Comment by remy** [comment]
damnit, blows up mac version: 

img

**Comment by remy** [comment]
I'll take a look on my side...

**Comment by remy** [comment]
Can you check on your side, if you change the line starting with:

```
echo "\033[${p};0f$(curl 
```

To 

```
echo -e "\033[${p};0f$(curl 
```

Does it give you the same output?

**Comment by sirfoga** [comment]
Yeah, sorry, my bad, I committed a line that would fix the color problem too, check the new commit (added ```echo -e```): now it should work

**Comment by remy** [comment]
👍

**Pull request merged**
